name: CI-Polaris-Basic 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: 21
          architecture: x64
          cache: 'maven'
      
      - name: Polaris Scan
        uses: blackduck-inc/black-duck-security-scan@v2.0.0
        with:
          ### SCANNING: Required fields
          polaris_server_url: ${{ vars.POLARIS_SERVER_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polaris_assessment_types: "SAST"
          
          ### SCANNING: Optional fields
          polaris_application_name: "pixee"
          
          ### PULL REQUEST COMMENTS: Uncomment below to enable
          polaris_prComment_enabled: true 
          github_token: ${{ secrets.GITHUB_TOKEN }} # Required when PR comments is enabled

          ### SARIF report parameters
          polaris_reports_sarif_create: true
          polaris_upload_sarif_report: true
          
          ### Test Build-less mode
          #polaris_assessment_mode: SOURCE_UPLOAD
          
          ### Signature scan
          #polaris_test_sca_type: "SCA-SIGNATURE"
